import { drizzle } from 'drizzle-orm/mysql2';
import { menuCategories, menuItems } from '../drizzle/schema';

const db = drizzle(process.env.DATABASE_URL!);

async function seedMenu() {
  console.log('Seeding menu data...');

  // Insert categories
  const categories = await db.insert(menuCategories).values([
    { name: 'Starters', slug: 'starters', description: 'Begin your meal with our delicious appetizers', displayOrder: 1, isActive: true },
    { name: 'Main Courses', slug: 'mains', description: 'Hearty and flavorful main dishes', displayOrder: 2, isActive: true },
    { name: 'Sides', slug: 'sides', description: 'Perfect accompaniments to your meal', displayOrder: 3, isActive: true },
    { name: 'Desserts', slug: 'desserts', description: 'Sweet endings to your dining experience', displayOrder: 4, isActive: true },
    { name: 'Drinks', slug: 'drinks', description: 'Refreshing beverages', displayOrder: 5, isActive: true },
  ]);

  console.log('Categories inserted');

  // Insert menu items
  await db.insert(menuItems).values([
    // Starters
    {
      categoryId: 1,
      name: 'Puff Puff',
      slug: 'puff-puff',
      description: 'Sweet fried dough balls, a popular West African snack',
      price: '4.99',
      isVegan: true,
      isGlutenFree: false,
      isHalal: true,
      allergens: JSON.stringify(['gluten']),
      isAvailable: true,
      isFeatured: false,
      displayOrder: 1,
    },
    {
      categoryId: 1,
      name: 'Plantain Chips',
      slug: 'plantain-chips',
      description: 'Crispy fried plantain slices served with spicy pepper sauce',
      price: '5.99',
      isVegan: true,
      isGlutenFree: true,
      isHalal: true,
      allergens: JSON.stringify([]),
      isAvailable: true,
      isFeatured: false,
      displayOrder: 2,
    },
    {
      categoryId: 1,
      name: 'Suya Skewers',
      slug: 'suya-skewers',
      description: 'Spicy grilled meat skewers with peanut spice blend',
      price: '7.99',
      isVegan: false,
      isGlutenFree: true,
      isHalal: true,
      allergens: JSON.stringify(['peanuts']),
      isAvailable: true,
      isFeatured: true,
      displayOrder: 3,
    },
    
    // Main Courses
    {
      categoryId: 2,
      name: 'Jollof Rice with Chicken',
      slug: 'jollof-rice-chicken',
      description: 'Our signature one-pot rice dish cooked in rich tomato sauce with grilled chicken',
      price: '12.99',
      isVegan: false,
      isGlutenFree: true,
      isHalal: true,
      allergens: JSON.stringify([]),
      isAvailable: true,
      isFeatured: true,
      displayOrder: 1,
    },
    {
      categoryId: 2,
      name: 'Egusi Soup with Fufu',
      slug: 'egusi-soup-fufu',
      description: 'Traditional melon seed soup with assorted meat and fish, served with pounded yam',
      price: '14.99',
      isVegan: false,
      isGlutenFree: true,
      isHalal: true,
      allergens: JSON.stringify(['fish']),
      isAvailable: true,
      isFeatured: true,
      displayOrder: 2,
    },
    {
      categoryId: 2,
      name: 'Waakye',
      slug: 'waakye',
      description: 'Rice and beans cooked together, served with spaghetti, gari, and protein of choice',
      price: '11.99',
      isVegan: false,
      isGlutenFree: false,
      isHalal: true,
      allergens: JSON.stringify(['gluten']),
      isAvailable: true,
      isFeatured: false,
      displayOrder: 3,
    },
    {
      categoryId: 2,
      name: 'Pepper Soup',
      slug: 'pepper-soup',
      description: 'Spicy broth with goat meat and aromatic herbs',
      price: '13.99',
      isVegan: false,
      isGlutenFree: true,
      isHalal: true,
      allergens: JSON.stringify([]),
      isAvailable: true,
      isFeatured: false,
      displayOrder: 4,
    },
    {
      categoryId: 2,
      name: 'Vegetable Jollof',
      slug: 'vegetable-jollof',
      description: 'Flavorful jollof rice loaded with mixed vegetables',
      price: '10.99',
      isVegan: true,
      isGlutenFree: true,
      isHalal: true,
      allergens: JSON.stringify([]),
      isAvailable: true,
      isFeatured: false,
      displayOrder: 5,
    },
    
    // Sides
    {
      categoryId: 3,
      name: 'Fried Plantain',
      slug: 'fried-plantain',
      description: 'Sweet ripe plantains fried to perfection',
      price: '3.99',
      isVegan: true,
      isGlutenFree: true,
      isHalal: true,
      allergens: JSON.stringify([]),
      isAvailable: true,
      isFeatured: false,
      displayOrder: 1,
    },
    {
      categoryId: 3,
      name: 'Moi Moi',
      slug: 'moi-moi',
      description: 'Steamed bean pudding with spices',
      price: '4.99',
      isVegan: true,
      isGlutenFree: true,
      isHalal: true,
      allergens: JSON.stringify([]),
      isAvailable: true,
      isFeatured: false,
      displayOrder: 2,
    },
    {
      categoryId: 3,
      name: 'Coleslaw',
      slug: 'coleslaw',
      description: 'Fresh cabbage and carrot salad',
      price: '2.99',
      isVegan: true,
      isGlutenFree: true,
      isHalal: true,
      allergens: JSON.stringify([]),
      isAvailable: true,
      isFeatured: false,
      displayOrder: 3,
    },
    
    // Desserts
    {
      categoryId: 4,
      name: 'Chin Chin',
      slug: 'chin-chin',
      description: 'Crunchy fried dough snack, lightly sweetened',
      price: '3.99',
      isVegan: true,
      isGlutenFree: false,
      isHalal: true,
      allergens: JSON.stringify(['gluten']),
      isAvailable: true,
      isFeatured: false,
      displayOrder: 1,
    },
    {
      categoryId: 4,
      name: 'Coconut Candy',
      slug: 'coconut-candy',
      description: 'Sweet coconut treats',
      price: '2.99',
      isVegan: true,
      isGlutenFree: true,
      isHalal: true,
      allergens: JSON.stringify([]),
      isAvailable: true,
      isFeatured: false,
      displayOrder: 2,
    },
    
    // Drinks
    {
      categoryId: 5,
      name: 'Chapman',
      slug: 'chapman',
      description: 'Nigerian fruit punch with a blend of citrus and grenadine',
      price: '3.99',
      isVegan: true,
      isGlutenFree: true,
      isHalal: true,
      allergens: JSON.stringify([]),
      isAvailable: true,
      isFeatured: false,
      displayOrder: 1,
    },
    {
      categoryId: 5,
      name: 'Zobo',
      slug: 'zobo',
      description: 'Refreshing hibiscus drink',
      price: '2.99',
      isVegan: true,
      isGlutenFree: true,
      isHalal: true,
      allergens: JSON.stringify([]),
      isAvailable: true,
      isFeatured: false,
      displayOrder: 2,
    },
    {
      categoryId: 5,
      name: 'Palm Wine',
      slug: 'palm-wine',
      description: 'Traditional fermented palm sap',
      price: '4.99',
      isVegan: true,
      isGlutenFree: true,
      isHalal: false,
      allergens: JSON.stringify([]),
      isAvailable: true,
      isFeatured: false,
      displayOrder: 3,
    },
  ]);

  console.log('Menu items inserted successfully!');
}

seedMenu().catch(console.error);
